### PR TITLE
For loop optimization with length caching and prefix operator

### PR DESCRIPTION
**Pull request by vctfernandes**
Great project, really helpful!

May I suggest two really small performance improvements?
Implemented length caching and prefix operator (++i) in all the for
loops, which should result in a small performance improvement according
to
http://stackoverflow.com/questions/5349425/whats-the-fastest-way-to-loop-through-an-array-in-javascript

### CODE REVIEW

**Comment by efkan** [comment]
Hi @vctfernandes ,

Thank you for contributing! 

Also thank you for teaching a new programming trick.

This change provides really small performance. I compared both of ways by looping 30,000,000 times on jsfiddle (https://jsfiddle.net/59jwd0c8/8/). It means 30,000,000 character in content-filter. It'is too big data. 

And caching the length provides 15 ms. advantage to me on my computer.
So, if 300,000 concurrent connections post 100 characters at the same moment to the server each user experiences 15 / 300,000 ms lag. 

Whereas, the developers (like you/me/us) read the code more difficult. 

So, I choose more readable, simple code. 

What do you think about that?

**Comment by vctfernandes** [comment]
Maybe I should have benchmarked it myself before suggesting it with my big mouth 😅

I'm with you on that. No need to sacrifice readability for such a small performance gain.

**Comment by efkan** [comment]
No problem. Every PR make me happy :)

Also everything changes fastly. This PR should be stay here.

Thanks.

**Comment by efkan** [comment]
I'm closing this PR because I've updated the main package.

**Pull request closed without merging**
